- alias: Roof Lights in sync with Roof Trapdoor OPEN
  trigger:
  - platform: state
    entity_id: cover.roof_trap_door
    to: open
  - platform: state
    entity_id: cover.roof_trap_door
    to: opening
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.roof_light_bottom
  - service: light.turn_on
    entity_id: light.roof_light_top
  id: 017f60047bb14564b5fb86529ceee472
- alias: Roof Lights in sync with Roof Trapdoor CLOSE
  trigger:
  - platform: state
    entity_id: cover.roof_trap_door
    to: closed
  - platform: state
    entity_id: cover.roof_trap_door
    to: closing
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.roof_light_bottom
  - service: light.turn_off
    entity_id: light.roof_light_top
  - service: switch.turn_off
    entity_id: switch.roof_right_table_power_relay
  id: b9266f900ff54e1f943713d1a30763fe
- id: '1706889626932'
  alias: Main Bathroom Light NSPanel Configuration
  description: ''
  use_blueprint:
    path: Blackymas/nspanel_blueprint.yaml
    input:
      weather_entity: weather.accuweather
      indoortemp: sensor.hallway_temperature
      climate: climate.hvac_upstairs
      left_button_entity: switch.main_bathroom_light_nspanel_relay_1
      left_button_name: Ceiling Light
      right_button_entity: switch.main_bathroom_light_nspanel_relay_2
      right_button_name: Wall Light
      entitypages_enabled: true
      nspanel_name: 62a05de4f818fc17d6faa360e9cfe490
      home_value03: sensor.water_boiler_temperature_in_from_panel
      chip01: binary_sensor.water_boiler_power_pump_controller_status
      relay_1_local_fallback: true
      relay_2_local_fallback: true
      climate_button08_icon: ''
      chip02: binary_sensor.water_boiler_power_wall_switch_status
      chip02_icon: mdi:water-boiler
      chip01_icon: mdi:pump
      entity01: light.ella_light
      entity02: light.tomer_light
      entity03: light.noga_light
      entity04: light.master_bedroom_left_light
      entity05: light.master_bedroom_right_light
      entities_entity01: sensor.water_boiler_temperature_in_from_panel
      entities_entity02: sensor.water_boiler_temperature_panel_out
      entities_entity03: sensor.water_boiler_temperature_out_to_panel
      entity_page01_label: Water Boiler Temperatures
      entities_entity01_icon: ''
      entities_entity02_name: Panel out
      entities_entity03_name: Out to panel
      entities_entity01_name: In from panel
      home_value03_icon: mdi:water-boiler
      chip02_inverted: false
      chip01_inverted: false
      chip07: binary_sensor.nuki_home_door_locked
      chip07_inverted: false
      chip07_icon: mdi:lock-open
      chip07_icon_color:
      - 255
      - 0
      - 0
      chip02_icon_color:
      - 255
      - 0
      - 0
      date_format: '%A, %d/%m'
