# lovelace_gen

#kiosk_mode:
#  hide_header: true
#  hide_menubutton: true
#  hide_overflow: true

title: Mobile

views:
  - !include lovelace_mobile_UI/weather_calendar.yaml
  - !include lovelace_mobile_UI/lights.yaml
  - !include lovelace_mobile_UI/covers.yaml
  - !include lovelace_mobile_UI/irrigation.yaml
  - !include lovelace_mobile_UI/hvac.yaml
  - !include lovelace_mobile_UI/vacuum.yaml
  - !include lovelace_mobile_UI/waterboiler.yaml
  - !include lovelace_mobile_UI/water_consumption.yaml
  - !include lovelace_mobile_UI/electricity_consumption.yaml
  - !include lovelace_mobile_UI/updates.yaml
