# UART for TUYA Dimmer
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# Register the Tuya MCU connection
tuya:

light:
  - platform: tuya
    name: "${friendly_name}"
    switch_datapoint: 1
    dimmer_datapoint: 2
    min_value: 25
    max_value: 255
    restore_mode: ALWAYS_OFF
