##############################################################
#   Custom Boiler Temperature functionality * numbers are GPIO#
##############################################################
#
# Spare : TX GPIO01 (TX)
# Spare : RX GPIO03 (RX)
# Spare : D1 GPIO05 (SCL)    - IO
# Spare : D2 GPIO04 (SDA)    - IO
# Spare : D3 GPIO00 (FLASH)  - IO, 10K Pull-up
# Spare : D4 GPIO02 ()       - IO, 10K Pull-up, Built-in LED

# Spare : A0 ADC0 ()         - Max 3.3v internal 100/320 divider
# Spare : D0 GPIO16 (WAKEUP) - IO
# Spare : D5 GPIO14 (SCK)    - IO
# Spare : D6 GPIO12 (MISO)   - IO
# Spare : D7 GPIO13 (MOSI)   - IO
# Spare : D8 GPIO15 (CS/SS)  - 10K Pull-down
#
# * All IOO have interrupt/pwm/I2C/one-wire support except D0
#
##############################################################
