#All ESP8266 inputs

binary_sensor:

  - platform: gpio
    id: input_gpio01
    pin:
      number: GPIO01

  - platform: gpio
    id: input_gpio03
    pin:
      number: GPIO03

  - platform: gpio
    id: input_gpio05
    pin:
      number: GPIO05

  - platform: gpio
    id: input_gpio04
    pin:
      number: GPIO04

  - platform: gpio
    id: input_gpio00
    pin:
      number: GPIO00

  - platform: gpio
    id: input_gpio02
    pin:
      number: GPIO02

  - platform: gpio
    id: input_gpio14
    pin:
      number: GPIO14

  - platform: gpio
    id: input_gpio12
    pin:
      number: GPIO12

  - platform: gpio
    id: input_gpio13
    pin:
      number: GPIO13

  - platform: gpio
    id: input_gpio15
    pin:
      number: GPIO15

  - platform: gpio
    id: input_gpio16
    pin:
      number: GPIO16
