substitutions:
  platform: ESP8266
  board: d1_mini
  device_name: kitchen-light-klapa
  friendly_name: "Kitchen Light Klapa"
  static_ip: 192.168.1.48
  esp8266_restore_from_flash: "FALSE" # "TRUE" / "FALSE" !!! Make sure that all switches, lights, fans, globals, etc... are set to ALWAYS_ON/OFF to minimize flash write cycles
  comment: "DIY modules based on Wemos D1 Mini"
  area: "Kitchen"

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  platform: !include zzz_common_files/platform_esp8266.yaml
  common: !include zzz_common_files/common.yaml

##############################################################
#   Wemos D1 Mini * numbers are GPIO#
##############################################################
#
# Status LED: GPIO02
# Button:     GPIO12
# Relay:      GPIO05
#
##############################################################

status_led:
  pin:
    number: GPIO02
    inverted: True

binary_sensor:
  - platform: gpio
    id: button
    internal: TRUE
    pin:
      number: GPIO12
      inverted: TRUE
      mode: INPUT_PULLUP
    filters:
      - delayed_on: 100ms
    on_press:
      - light.toggle: light_output
    on_release:
      - light.toggle: light_output
    # on_click:
    # # - min_length: ${blue_led_hold_min}s
    # #   max_length: ${blue_led_hold_max}s
    # #   then:
    # #     - switch.toggle: blue_led
    # - min_length: ${reset_hold_min}s
    #   max_length: ${reset_hold_max}s
    #   then:
    #     - switch.turn_on: restart_device

output:
  - platform: gpio
    pin: GPIO05
    inverted: false
    id: relay

light:
  - platform: binary
    id: light_output
    name: "${friendly_name}"
    output: relay
    restore_mode: ALWAYS_OFF
