substitutions:
  device_name: livingroom-wall-light
  friendly_name: "Livingroom Wall Light"
  static_ip: 192.168.1.70
  onoff_toggle: "toggle"

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_mini.yaml
