substitutions:
  device_name: main-bathroom-light-nspanel
  friendly_name: "Main Bathroom Light NSPanel"
  # static_ip: 192.168.1.24
  comment: "Main Bathroom Light Switch based on NSPanel"

# Core and optional configurations
packages:
  # common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_nspanel.yaml
