substitutions:
  device_name: main-bathroom-light-nspanel
  friendly_name: "Main Bathroom Light NSPanel"
  # static_ip: 192.168.1.24

# Core and optional configurations
packages:
  # common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_nspanel.yaml


# substitutions:
#   # Settings - Editable values
#   device_name: main-bathroom-light-nspanel
#   wifi_ssid: !secret WIFI_SSID_1
#   wifi_password: !secret WIFI_Password_1
#   nextion_update_url: "http://homeassistant.local:8123/local/nspanel_eu.tft"  # Optional for `esp-idf` framework
#   # Add-on configuration (if needed)
#   # heater_relay: "1"  # Possible values: "1" or "2"

# # Customization area
# ##### My customization - Start #####
# ##### My customization - End #####

# # Core and optional configurations
# packages:
#   remote_package:
#     url: https://github.com/Blackymas/NSPanel_HA_Blueprint
#     ref: main
#     files:
#       - nspanel_esphome.yaml # Core package
#       # Optional advanced and add-on configurations
#       # - advanced/esphome/nspanel_esphome_advanced.yaml
#       # - nspanel_esphome_addon_climate_cool.yaml
#       # - nspanel_esphome_addon_climate_heat.yaml
#       # - nspanel_esphome_addon_climate_dual.yaml
#     refresh: 300s

# esp32:
#   framework:
#     type: esp-idf