substitutions:
  device_name: master-bedroom-right-light
  friendly_name: "Master Bedroom Right Light"
  static_ip: 192.168.1.56
  onoff_toggle: "toggle"

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_minir4.yaml
