substitutions:
  device_name: patio_light
  friendly_name: "Patio Light"
  static_ip: 192.168.1.35

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_lightswitch_wfws02.yaml