substitutions:
  device_name: roof_trapdoor
  friendly_name: "Roof Trap-Door"
  static_ip: 192.168.1.29
  # platform: ESP8266
  # board: esp01_1m
  # esp8266_restore_from_flash: "TRUE" # "TRUE" / "FALSE" !!! Make sure that all switches, lights, fans, globals, etc... are set to ALWAYS_ON/OFF to minimize flash write cycles

  # Applicable for Curtain Switches
  duration_open: "22" # Actually 19
  duration_close: "22" # Actually 19

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_shutterswitch_wfcs01.yaml

# binary_sensor:

# - platform: gpio
#   id: button_open
#   internal: TRUE
#   pin:
#     number: GPIO12
#     inverted: TRUE
#     mode: INPUT_PULLUP
#   filters:
#     - delayed_on: 50ms
#   on_press:
#     - switch.turn_on: open_relay_l1
#     - switch.turn_off: close_relay_l3

# - platform: gpio
#   id: button_stop
#   internal: TRUE
#   pin:
#     number: GPIO03
#     inverted: TRUE
#     mode: INPUT_PULLUP
#   filters:
#     - delayed_on: 50ms
#   on_press:
#     - switch.turn_off: open_relay_l1
#     - switch.turn_off: close_relay_l3
#   on_click:
#   - min_length: ${blue_led_hold_min}s
#     max_length: ${blue_led_hold_max}s
#     then:
#       - switch.toggle: blue_led
#   - min_length: ${reset_hold_min}s
#     max_length: ${reset_hold_max}s
#     then:
#       - switch.turn_on: restart_device

# - platform: gpio
#   id: button_close
#   internal: TRUE
#   pin:
#     number: GPIO5
#     inverted: TRUE
#     mode: INPUT_PULLUP
#   filters:
#     - delayed_on: 50ms
#   on_press:
#     - switch.turn_off: open_relay_l1
#     - switch.turn_on: close_relay_l3

# # - platform: gpio
# #   pin: GPIO04
# #   internal: TRUE


# switch:

# - platform: gpio
#   pin: GPIO01
#   id: blue_led
#   internal: TRUE
#   restore_mode: RESTORE_DEFAULT_OFF

# - platform: gpio
#   pin: GPIO16
#   id: open_led
#   internal: TRUE
#   restore_mode: ALWAYS_OFF

# - platform: gpio
#   pin: GPIO14
#   id: stop_led
#   internal: TRUE
#   restore_mode: ALWAYS_OFF

# - platform: gpio
#   pin: GPIO2
#   id: close_led
#   internal: TRUE
#   restore_mode: ALWAYS_OFF

# # - platform: gpio
# #   pin: GPIO04
# #   name: "${friendly_name} GPIO04"
# #   internal: TRUE
# #   restore_mode: ALWAYS_OFF

# - platform: gpio
#   pin: GPIO13
#   id: open_relay_l1
#   internal: TRUE
#   restore_mode: ALWAYS_OFF

# - platform: gpio
#   pin: GPIO15
#   id: close_relay_l3
#   internal: TRUE
#   restore_mode: ALWAYS_OFF
