substitutions:
  device_name: sonoff-mini-3
  friendly_name: "sonoff-mini-3"
  static_ip: 192.168.1.65
  onoff_toggle: "toggle"

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_mini.yaml
