substitutions:
  device_name: spare-boiler-switch
  friendly_name: "Spare Boiler Switch"
  static_ip: 192.168.1.59
  max_duration_on: 240min # Limit switch ON time

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_boilerswitch_wfbs01.yaml
