substitutions:
  device_name: spare_double_light
  friendly_name: "Spare Double Light"
  static_ip: 192.168.1.62

  #MQTT_broker_topic_prefix: myhome/test # myhome/<Floor>/<Room>/<Function>/<Location>

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_lightswitch_wfws02.yaml
