substitutions:
  device_name: stairs-light
  friendly_name: "Stairs Light"
  static_ip: 192.168.1.57
  onoff_toggle: "toggle"

packages:
  common: !include zzz_common_files/common.yaml
  family: !include zzz_common_files/common_sonoff_minir4.yaml
