sensor:
  - platform: waze_travel_time
    origin: !secret waze_home_coordinates
    destination: !secret waze_work_d_coordinates
    region: 'IL'
    name: Work Dan
    realtime: true
    vehicle_type: car
    avoid_ferries: true
    avoid_toll_roads: true
    avoid_subscription_roads: true

  - platform: waze_travel_time
    origin: !secret waze_home_coordinates
    destination: !secret waze_work_a_coordinates
    region: 'IL'
    name: Work Aviva
    realtime: true
    vehicle_type: car
    avoid_ferries: true
    avoid_toll_roads: true
    avoid_subscription_roads: true

  - platform: waze_travel_time
    origin: !secret waze_home_coordinates
    destination: !secret waze_ky_coordinates
    region: 'IL'
    name: Kfar Yona
    realtime: true
    vehicle_type: car
    avoid_ferries: true
    avoid_toll_roads: true
    avoid_subscription_roads: true

  - platform: waze_travel_time
    origin: !secret waze_home_coordinates
    destination: !secret waze_pt_coordinates
    region: 'IL'
    name: Petach Tikva
    realtime: true
    vehicle_type: car
    avoid_ferries: true
    avoid_toll_roads: true
    avoid_subscription_roads: true

  - platform: template
    sensors:
      work_dan_ui:
        unit_of_measurement: 'm'
        value_template: "{{ states('sensor.work_dan') | round(0) }}"
      work_aviva_ui:
        unit_of_measurement: 'm'
        value_template: "{{ states('sensor.work_aviva') | round(0) }}"
      kfar_yona_ui:
        unit_of_measurement: 'm'
        value_template: "{{ states('sensor.kfar_yona') | round(0) }}"
      petach_tikva_ui:
        unit_of_measurement: 'm'
        value_template: "{{ states('sensor.petach_tikva') | round(0) }}"
