#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  hvac_hallway_scheduler_enable1:
    name: Enable
    icon: mdi:power

input_datetime:
  hvac_hallway_start_time1:
    name: Start Time
    has_date: false
    has_time: true

climate:
  - platform: smartir
    name: HVAC Hallway Virtual 1
    unique_id: hvac_hallway_virtual1
    device_code: 1621
    controller_data: remote.hallway_remote
    # temperature_sensor:
    delay: 10

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  description: "HVAC Hallway Scheduler 1"
  alias: hvac_hallway_scheduler1
  use_blueprint:
    path: blueprint_hvac_scheduler.yaml
    input:
      start_time: input_datetime.hvac_hallway_start_time1
      scheduler_enable: input_boolean.hvac_hallway_scheduler_enable1
      virtual_climate: climate.hvac_hallway_virtual_1
      target_climate: climate.hvac_hallway

###################################
########## S C R I P T S ##########
###################################

# script:
# # ---------------------
