#####################################
########## E N T I T I E S ##########
#####################################

input_number:
  mfc_j470dw_ink_low_limit:
    name: Brother MFC-J470DW Ink Low Level Limit
    unit_of_measurement: "%"
    min: 10
    max: 90
    step: 10

sensor:
  - platform: template
    sensors:
      mfc_j470dw_ink_low:
        icon_template: mdi:printer-alert
        value_template: >
          {% set devices =['sensor.mfc_j470dw_black_ink_remaining',
                           'sensor.mfc_j470dw_cyan_ink_remaining',
                           'sensor.mfc_j470dw_magenta_ink_remaining',
                           'sensor.mfc_j470dw_yellow_ink_remaining'] %}
          {% set mfc_j470dw_ink_low = namespace(count=0) %}
          {% for entity_id in devices %}
            {% if ((states(entity_id) != 'unavailable') and (states(entity_id) | int) <= (states('input_number.mfc_j470dw_ink_low_limit') | int)) %}
              {% set mfc_j470dw_ink_low.count = mfc_j470dw_ink_low.count + 1 %}
            {% endif %}
          {% endfor %}
          {{ mfc_j470dw_ink_low.count }}


###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  - alias: Printer Ink Level Below Limit
    description: Printer Ink Level Below Limit
    trigger:
      platform: template
      value_template: "{{ (states('sensor.mfc_j470dw_ink_low') | int) > 0 }}"
    condition: []
    action:
      - service: notify.email
        data_template:
          message: Printer ink level below limit. Black={{ sensor.mfc_j470dw_black_ink_remaining }}%, Cyan={{ sensor.mfc_j470dw_cyan_ink_remaining }}%, Magenta={{ sensor.mfc_j470dw_magenta_ink_remaining }}%, Yellow={{ sensor.mfc_j470dw_yellow_ink_remaining }}%

###################################
########## S C R I P T S ##########
###################################

# script:
# # ---------------------
