#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  boiler_switch_scheduler_enable1:
    name: Enable
    icon: mdi:power
  boiler_switch_day_sunday1:
    name: Sunday
    icon: mdi:calendar-today
  boiler_switch_day_monday1:
    name: Monday
    icon: mdi:calendar-today
  boiler_switch_day_tuesday1:
    name: Tuesday
    icon: mdi:calendar-today
  boiler_switch_day_wednesday1:
    name: Wednesday
    icon: mdi:calendar-today
  boiler_switch_day_thursday1:
    name: Thursday
    icon: mdi:calendar-today
  boiler_switch_day_friday1:
    name: Friday
    icon: mdi:calendar-today
  boiler_switch_day_saturday1:
    name: Saturday
    icon: mdi:calendar-today

input_datetime:
  boiler_switch_start_time1:
    name: Start Time
    has_date: false
    has_time: true

input_number:
  boiler_switch_timer_duration1:
    name: Duration
    unit_of_measurement: "min"
    min: 0
    max: 180
    step: 5

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  - alias: water_boiler_scheduler1
    description: "Water Boiler Scheduler 1"
    use_blueprint:
      path: blueprint_waterboiler_scheduler.yaml
      input:
        start_time: input_datetime.boiler_switch_start_time1
        scheduler_enable: input_boolean.boiler_switch_scheduler_enable1
        switch: switch.boiler_switch
        timer: timer.boiler_switch
        duration: input_number.boiler_switch_timer_duration1
        scheduler_number: 1

###################################
########## S C R I P T S ##########
###################################

# script:
#   # ---------------------
