#####################################
########## E N T I T I E S ##########
#####################################

group:
  irrigation: # Used for UI button
    name: Irrigation Valves
    icon: mdi:sprinkler
    all: false
    entities:
      - switch.irrigation_sprinkler_west
      - switch.irrigation_sprinkler_north
      - switch.irrigation_drips

template:
  - sensor:
    - name: irrigation_sprinkler_west_problem
      icon: mdi:sprinkler
      state: >
        {% if has_value('switch.irrigation_sprinkler_west') %}
          {{ 0 }}
        {% else %}
          {{ 1 }}
        {% endif %}
    - name: irrigation_sprinkler_north_problem
      icon: mdi:sprinkler
      state: >
        {% if has_value('switch.irrigation_sprinkler_north') %}
          {{ 0 }}
        {% else %}
          {{ 1 }}
        {% endif %}
    - name: irrigation_drips_problem
      icon: mdi:water
      state: >
        {% if has_value('switch.irrigation_drips') %}
          {{ 0 }}
        {% else %}
          {{ 1 }}
        {% endif %}

input_number:
  irrigation_duration:
    name: Duration
    unit_of_measurement: "sec"
    initial: 900
    min: 60
    max: 1800
    step: 60

input_boolean:
  irrigation_sprinkler_north:
    name: North Sprinklers
    icon: mdi:sprinkler
  irrigation_sprinkler_west:
    name: West Sprinklers
    icon: mdi:sprinkler
  irrigation_drips:
    name: Drips
    icon: mdi:water
  irrigation_immediate:
    name: Irrigation Immediate
    icon: mdi:power
  irrigation_future:
    name: Irrigation Future
    icon: mdi:timer-outline

timer:
  irrigation_sprinkler_north: # For schedulers
    # name: Time Left
    icon: mdi:timer-outline
  irrigation_sprinkler_west: # For schedulers
    # name: Time Left
    icon: mdi:timer-outline
  irrigation_drips: # For schedulers
    # name: Time Left
    icon: mdi:timer-outline

input_datetime:
  irrigation_start_time:
    name: Start Time
    has_time: true
    has_date: false

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  # Trigger    - HA initializing
  # Conditions - NONE
  # Actions    - Turn off all irrigation valves (in case HA restart during a watering cycle)
  - alias: Irrigataion Initialization
    description: Update enitity values upon HA start
    triggers:
      - trigger: homeassistant
        event: start
    conditions: []
    actions:
      - action: switch.turn_off
        entity_id: switch.irrigation_sprinkler_west
      - action: switch.turn_off
        entity_id: switch.irrigation_sprinkler_north
      - action: switch.turn_off
        entity_id: switch.irrigation_drips
        

  # Trigger    - Directly turn ON Irrigation Valve
  # Conditions - No timer running
  # Actions    - Start Timer
  #            - Turn OFF Irrigation Valve after timer expires
  - alias: Irrigation  Sprinkler West Direct Start
    description: "Irrigation Sprinkler WestDirect Start"
    use_blueprint:
      path: blueprint_time_limit_activation.yaml
      input:
        switch: switch.irrigation_sprinkler_west
        timer: timer.irrigation_sprinkler_west
        max_limit: input_number.ui_irrigation_max_time_limit

  - alias: Irrigation Sprinkler North Direct Start
    description: "Irrigation Sprinkler North Direct Start"
    use_blueprint:
      path: blueprint_time_limit_activation.yaml
      input:
        switch: switch.irrigation_sprinkler_north
        timer: timer.irrigation_sprinkler_north
        max_limit: input_number.ui_irrigation_max_time_limit

  - alias: Irrigation Drips Direct Start
    description: "Irrigation Drips Direct Start"
    use_blueprint:
      path: blueprint_time_limit_activation.yaml
      input:
        switch: switch.irrigation_drips
        timer: timer.irrigation_drips
        max_limit: input_number.ui_irrigation_max_time_limit

  # Trigger - Irrigation valve turned off
  # Conditions - NONE
  # Actions - Finish irrigation valve timer
  - alias: Irrigation Valve OFF
    description: BLA BLA BLA
    triggers:
      - trigger: state
        entity_id: switch.irrigation_sprinkler_west
        to: "off"
        id: west
      - trigger: state
        entity_id: switch.irrigation_sprinkler_north
        to: "off"
        id: north
      - trigger: state
        entity_id: switch.irrigation_drips
        to: "off"
        id: drips
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: trigger
                id: west
            sequence:
              - action: timer.finish
                entity_id: timer.irrigation_sprinkler_west
          - conditions:
              - condition: trigger
                id: north
            sequence:
              - action: timer.finish
                entity_id: timer.irrigation_sprinkler_north
          - conditions:
              - condition: trigger
                id: drips
            sequence:
              - action: timer.finish
                entity_id: timer.irrigation_drips

  # Trigger - Immediate turn ON Irrigation
  # Conditions - NONE
  # Actions
  - alias: Irrigation Immediate Start Cycle
    description: "Irrigation Immediate Start Cycle"
    triggers:
      - trigger: state
        entity_id: input_boolean.irrigation_immediate
        from: "off"
        to: "on"
    conditions: []
    actions:
      - action: notify.send_message
        data:
          entity_id: notify.file_debug
          message: "Starting Manual Immediate start_irrigation_cycle script"
      - action: script.turn_on
        entity_id: script.start_irrigation_cycle
      - delay: "00:00:01"
      - wait_template: "{{ is_state('script.start_irrigation_cycle', 'off') }}"
      - action: notify.send_message
        data:
          entity_id: notify.file_debug
          message: "Completed Manual Immediate start_irrigation_cycle script"

  # Trigger - Turning ON Timer Scheduled Switch
  # Conditions - NONE
  # Actions
  - alias: Irrigation Future Start Cycle
    description: "Irrigation Manual Scheduled Start Cycle"
    triggers:
      - trigger: time
        at: input_datetime.irrigation_start_time
    conditions:
      condition: state
      entity_id: input_boolean.irrigation_future
      state: "on"
    actions:
      - action: notify.send_message
        data:
          entity_id: notify.file_debug
          message: "Starting Manual Future start_irrigation_cycle script"
      - action: script.turn_on
        entity_id: script.start_irrigation_cycle
      - delay: "00:00:01"
      - wait_template: "{{ is_state('script.start_irrigation_cycle', 'off') }}"
      - action: notify.send_message
        data:
          entity_id: notify.file_debug
          message: "Completed Manual Future start_irrigation_cycle script"

  # Trigger - Turning OFF Timer Start/Stop Switch
  # Conditions - NONE
  # Actions
  #         - Run stop script with parameter all irrigation valves control entities
  - alias: Irrigation Stop Manual Cycle
    description: "Irrigation Stop Manual Cycle"
    triggers:
      - trigger: state
        entity_id: input_boolean.irrigation_immediate
        to: "off"
      - trigger: state
        entity_id: input_boolean.irrigation_future
        to: "off"
    conditions: []
    actions:
      - action: notify.send_message
        data:
          entity_id: notify.file_debug
          message: "stop_irrigation_cycle - Initiated"
      - action: script.turn_off
        entity_id: script.start_irrigation_cycle
      - action: input_boolean.turn_off
        entity_id: input_boolean.irrigation_immediate
      - action: input_boolean.turn_off
        entity_id: input_boolean.irrigation_future
      - repeat:
          for_each:
            - "irrigation_sprinkler_west"
            - "irrigation_sprinkler_north"
            - "irrigation_drips"
          sequence:
            - action: timer.finish
              target:
                entity_id: "timer.{{ repeat.item }}"
            - action: switch.turn_off
              target:
                entity_id: "switch.{{ repeat.item }}"
      - action: notify.send_message
        data:
          entity_id: notify.file_debug
          message: "stop_irrigation_cycle - Completed"

###################################
########## S C R I P T S ##########
###################################

script:
  # ---------------------
  start_irrigation_cycle:
    mode: restart
    sequence:
      - repeat:
          for_each:
            - "irrigation_sprinkler_west"
            - "irrigation_sprinkler_north"
            - "irrigation_drips"
          sequence:
            - if:
                - condition: template
                  value_template: "{{ is_state('input_boolean.' ~ repeat.item, 'on') }}"
              then:
                - action: notify.send_message
                  data:
                    entity_id: notify.file_debug
                    message: "Irrigation valve {{ repeat.item }} - Turned ON #"
                - action: switch.turn_on
                  target:
                    entity_id: "switch.{{ repeat.item }}"
                - action: timer.start
                  data:
                    entity_id: "timer.{{ repeat.item }}"
                    duration: #"{{ states('input_number.irrigation_duration') | int | timestamp_custom('%H:%M:%S',False) }}"
                      seconds: "{{ states('input_number.irrigation_duration') | int }}"
                - wait_template: "{{ is_state('timer.' ~ repeat.item, 'idle' ) }}"
                - action: switch.turn_off
                  target:
                    entity_id: "switch.{{ repeat.item }}"
                - action: notify.send_message
                  data:
                    entity_id: notify.file_debug
                    message: "Irrigation valve {{ repeat.item }} - Turned OFF #"
      - action: input_boolean.turn_off
        entity_id: input_boolean.irrigation_immediate
      - action: input_boolean.turn_off
        entity_id: input_boolean.irrigation_future
