#####################################
########## E N T I T I E S ##########
#####################################

group:
  irrigation: # Used for UI button
    name: Irrigation Valves
    icon: mdi:sprinkler
    all: false
    entities:
      - switch.irrigation_sprinkler_west
      - switch.irrigation_sprinkler_north
      - switch.irrigation_drips

sensor:
  - platform: template
    sensors:
      irrigation_sprinkler_west_problem:
        icon_template: mdi:sprinkler
        value_template: >
          {% if has_value('switch.irrigation_sprinkler_west') %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}
      irrigation_sprinkler_north_problem:
        icon_template: mdi:sprinkler
        value_template: >
          {% if has_value('switch.irrigation_sprinkler_north') %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}
      irrigation_drips_problem:
        icon_template: mdi:water
        value_template: >
          {% if has_value('switch.irrigation_drips') %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}

input_number:
  irrigation_duration:
    name: Duration
    unit_of_measurement: "sec"
    initial: 900
    min: 60
    max: 1800
    step: 60

input_boolean:
  irrigation_sprinkler_north:
    name: North Sprinklers
    icon: mdi:sprinkler
  irrigation_sprinkler_west:
    name: West Sprinklers
    icon: mdi:sprinkler
  irrigation_drips:
    name: Drips
    icon: mdi:water
  irrigation_immediate:
    name: Irrigation Immediate
    icon: mdi:power
  irrigation_future:
    name: Irrigation Future
    icon: mdi:timer-outline

timer:
  irrigation_sprinkler_north: # For schedulers
    # name: Time Left
    icon: mdi:timer-outline
  irrigation_sprinkler_west: # For schedulers
    # name: Time Left
    icon: mdi:timer-outline
  irrigation_drips: # For schedulers
    # name: Time Left
    icon: mdi:timer-outline

input_datetime:
  irrigation_start_time:
    name: Start Time
    has_time: true
    has_date: false

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  # Trigger    - HA initializing
  # Conditions - NONE
  # Actions    - Turn off all irrigation valves (in case HA restart during a watering cycle)
  - alias: Irrigataion Initialization
    description: Update enitity values upon HA start
    trigger:
      - event: start
        platform: homeassistant
    condition: []
    action:
      - entity_id: switch.irrigation_sprinkler_west
        service: switch.turn_off
      - entity_id: switch.irrigation_sprinkler_north
        service: switch.turn_off
      - entity_id: switch.irrigation_drips
        service: switch.turn_off

  # Trigger    - Directly turn ON Irrigation Valve
  # Conditions - No timer running
  # Actions    - Start Timer
  #            - Turn OFF Irrigation Valve after timer expires
  - alias: Irrigation  Sprinkler West Direct Start
    description: "Irrigation Sprinkler WestDirect Start"
    use_blueprint:
      path: blueprint_time_limit_activation.yaml
      input:
        switch: switch.irrigation_sprinkler_west
        timer: timer.irrigation_sprinkler_west
        max_limit: input_number.ui_irrigation_max_time_limit

  - alias: Irrigation Sprinkler North Direct Start
    description: "Irrigation Sprinkler North Direct Start"
    use_blueprint:
      path: blueprint_time_limit_activation.yaml
      input:
        switch: switch.irrigation_sprinkler_north
        timer: timer.irrigation_sprinkler_north
        max_limit: input_number.ui_irrigation_max_time_limit

  - alias: Irrigation Drips Direct Start
    description: "Irrigation Drips Direct Start"
    use_blueprint:
      path: blueprint_time_limit_activation.yaml
      input:
        switch: switch.irrigation_drips
        timer: timer.irrigation_drips
        max_limit: input_number.ui_irrigation_max_time_limit

  # Trigger - Irrigation valve turned off
  # Conditions - NONE
  # Actions - Finish irrigation valve timer
  - alias: Irrigation Valve OFF
    description: BLA BLA BLA
    trigger:
      - platform: state
        entity_id: switch.irrigation_sprinkler_west
        to: "off"
        id: west
      - platform: state
        entity_id: switch.irrigation_sprinkler_north
        to: "off"
        id: north
      - platform: state
        entity_id: switch.irrigation_drips
        to: "off"
        id: drips
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id: west
            sequence:
              - service: timer.finish
                entity_id: timer.irrigation_sprinkler_west
          - conditions:
              - condition: trigger
                id: north
            sequence:
              - service: timer.finish
                entity_id: timer.irrigation_sprinkler_north
          - conditions:
              - condition: trigger
                id: drips
            sequence:
              - service: timer.finish
                entity_id: timer.irrigation_drips

  # Trigger - Immediate turn ON Irrigation
  # Conditions - NONE
  # Actions
  - alias: Irrigation Immediate Start Cycle
    description: "Irrigation Immediate Start Cycle"
    trigger:
      - platform: state
        entity_id: input_boolean.irrigation_immediate
        from: "off"
        to: "on"
    condition: []
    action:
      - service: notify.file_debug
        data:
          message: "Starting Manual Immediate start_irrigation_cycle script"
      - service: script.turn_on
        entity_id: script.start_irrigation_cycle
      - delay: "00:00:01"
      - wait_template: "{{ is_state('script.start_irrigation_cycle', 'off') }}"
      - service: notify.file_debug
        data:
          message: "Completed Manual Immediate start_irrigation_cycle script"

  # Trigger - Turning ON Timer Scheduled Switch
  # Conditions - NONE
  # Actions
  - alias: Irrigation Future Start Cycle
    description: "Irrigation Manual Scheduled Start Cycle"
    trigger:
      - platform: time
        at: input_datetime.irrigation_start_time
    condition:
      condition: state
      entity_id: input_boolean.irrigation_future
      state: "on"
    action:
      - service: notify.file_debug
        data:
          message: "Starting Manual Future start_irrigation_cycle script"
      - service: script.turn_on
        entity_id: script.start_irrigation_cycle
      - delay: "00:00:01"
      - wait_template: "{{ is_state('script.start_irrigation_cycle', 'off') }}"
      - service: notify.file_debug
        data:
          message: "Completed Manual Future start_irrigation_cycle script"

  # Trigger - Turning OFF Timer Start/Stop Switch
  # Conditions - NONE
  # Actions
  #         - Run stop script with parameter all irrigation valves control entities
  - alias: Irrigation Stop Manual Cycle
    description: "Irrigation Stop Manual Cycle"
    trigger:
      - platform: state
        entity_id: input_boolean.irrigation_immediate
        to: "off"
      - platform: state
        entity_id: input_boolean.irrigation_future
        to: "off"
    condition: []
    action:
      - service: notify.file_debug
        data:
          message: "stop_irrigation_cycle - Initiated"
      - service: script.turn_off
        entity_id: script.start_irrigation_cycle
      - service: input_boolean.turn_off
        entity_id: input_boolean.irrigation_immediate
      - service: input_boolean.turn_off
        entity_id: input_boolean.irrigation_future
      - repeat:
          for_each:
            - "irrigation_sprinkler_west"
            - "irrigation_sprinkler_north"
            - "irrigation_drips"
          sequence:
            - service: timer.finish
              target:
                entity_id: "timer.{{ repeat.item }}"
            - service: switch.turn_off
              target:
                entity_id: "switch.{{ repeat.item }}"
      - service: notify.file_debug
        data:
          message: "stop_irrigation_cycle - Completed"

###################################
########## S C R I P T S ##########
###################################

script:
  # ---------------------
  start_irrigation_cycle:
    mode: restart
    sequence:
      - repeat:
          for_each:
            - "irrigation_sprinkler_west"
            - "irrigation_sprinkler_north"
            - "irrigation_drips"
          sequence:
            - if:
                - condition: template
                  value_template: "{{ is_state('input_boolean.' ~ repeat.item, 'on') }}"
              then:
                - service: notify.file_debug
                  data:
                    message: "Irrigation valve {{ repeat.item }} - Turned ON #"
                - service: switch.turn_on
                  target:
                    entity_id: "switch.{{ repeat.item }}"
                - service: timer.start
                  data:
                    entity_id: "timer.{{ repeat.item }}"
                    duration: #"{{ states('input_number.irrigation_duration') | int | timestamp_custom('%H:%M:%S',False) }}"
                      seconds: "{{ states('input_number.irrigation_duration') | int }}"
                - wait_template: "{{ is_state('timer.' ~ repeat.item, 'idle' ) }}"
                - service: switch.turn_off
                  target:
                    entity_id: "switch.{{ repeat.item }}"
                - service: notify.file_debug
                  data:
                    message: "Irrigation valve {{ repeat.item }} - Turned OFF #"
      - service: input_boolean.turn_off
        entity_id: input_boolean.irrigation_immediate
      - service: input_boolean.turn_off
        entity_id: input_boolean.irrigation_future
