#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  hvac_downstairs_scheduler_enable4:
    name: Enable
    icon: mdi:power

input_datetime:
  hvac_downstairs_start_time4:
    name: Start Time
    has_date: false
    has_time: true

climate:
  - platform: smartir
    name: HVAC Downstairs Virtual 4
    unique_id: hvac_downstairs_virtual4
    device_code: 1621
    controller_data: remote.downstairs_remote
    # temperature_sensor:
    delay: 10

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  description: "HVAC Downstairs Scheduler 4"
  alias: hvac_downstairs_scheduler4
  use_blueprint:
    path: blueprint_hvac_scheduler.yaml
    input:
      start_time: input_datetime.hvac_downstairs_start_time4
      scheduler_enable: input_boolean.hvac_downstairs_scheduler_enable4
      virtual_climate: climate.hvac_downstairs_virtual_4
      target_climate: climate.hvac_downstairs

###################################
########## S C R I P T S ##########
###################################

# script:
# # ---------------------
