#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  boiler_switch_scheduler_enable2:
    name: Enable
    icon: mdi:power
  boiler_switch_day_sunday2:
    name: Sunday
    icon: mdi:calendar-today
  boiler_switch_day_monday2:
    name: Monday
    icon: mdi:calendar-today
  boiler_switch_day_tuesday2:
    name: Tuesday
    icon: mdi:calendar-today
  boiler_switch_day_wednesday2:
    name: Wednesday
    icon: mdi:calendar-today
  boiler_switch_day_thursday2:
    name: Thursday
    icon: mdi:calendar-today
  boiler_switch_day_friday2:
    name: Friday
    icon: mdi:calendar-today
  boiler_switch_day_saturday2:
    name: Saturday
    icon: mdi:calendar-today

input_datetime:
  boiler_switch_start_time2:
    name: Start Time
    has_date: false
    has_time: true

input_number:
  boiler_switch_timer_duration2:
    name: Duration
    unit_of_measurement: "min"
    min: 0
    max: 180
    step: 5

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  description: "Water Boiler Scheduler 2"
  alias: water_boiler_scheduler2
  use_blueprint:
    path: blueprint_waterboiler_scheduler.yaml
    input:
      start_time: input_datetime.boiler_switch_start_time2
      scheduler_enable: input_boolean.boiler_switch_scheduler_enable2
      switch: switch.boiler_switch
      timer: timer.boiler_switch
      duration: input_number.boiler_switch_timer_duration2
      scheduler_number: 2

###################################
########## S C R I P T S ##########
###################################

# script:
#   # ---------------------
