#####################################
########## E N T I T I E S ##########
#####################################

sensor:
  - platform: template
    sensors:
      hvac_livingroom_problem:
        icon_template: mdi:air-conditioner
        value_template: >
          {% if (has_value('sensor.livingroom_temperature')) %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}
      hvac_hallway_problem:
        icon_template: mdi:air-conditioner
        value_template: >
          {% if (has_value('sensor.hallway_temperature')) %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}

climate:
  - platform: smartir
    name: HVAC Livingroom
    unique_id: hvac_livingroom
    device_code: 1620
    controller_data: remote.livingroom
    temperature_sensor: sensor.livingroom_temperature

  - platform: smartir
    name: HVAC Hallway
    unique_id: hvac_hallway
    device_code: 1620
    controller_data: remote.hallway
    temperature_sensor: sensor.hallway_temperature

###########################################
########## A U T O M A T I O N S ##########
###########################################

# automation:

###################################
########## S C R I P T S ##########
###################################

# script:
# # ---------------------
