#####################################
########## E N T I T I E S ##########
#####################################

sensor:
  - platform: template
    sensors:
      water_consumption_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if ( (states('sensor.water_consumption_daily_limit_exceeded') == '1') or (states('sensor.water_consumption_hourly_limit_exceeded') == '1') or (states('sensor.water_consumption_monthly_limit_exceeded') == '1') or (states('sensor.water_consumption_monthly_prediction_limit_exceeded') == '1') ) %}
            1
          {% else %}
            0
          {% endif %}

      water_consumption_daily_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if ((states('sensor.water_meter_16452690_today_s_consumption') == 'unavailable') or (states('sensor.water_meter_16452690_today_s_consumption') == 'unknown') or (states('sensor.water_meter_16452690_today_s_consumption') | float) < (states('input_number.water_consumption_daily_limit') | float)) %}
            0
          {% else %}
            1
          {% endif %}

      water_consumption_hourly_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if ((states('sensor.water_consumption_hourly') == 'unavailable') or (states('sensor.water_consumption_hourly') == 'unknown') or (states('sensor.water_consumption_hourly') | float) < (states('input_number.water_consumption_hourly_limit') | float)) %}
            0
          {% else %}
            1
          {% endif %}
    
      water_consumption_monthly_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if ((states('sensor.water_meter_16452690_monthly_consumption') == 'unavailable') or (states('sensor.water_meter_16452690_monthly_consumption') == 'unknown') or  (states('sensor.water_meter_16452690_monthly_consumption') | float) < (states('input_number.water_consumption_monthly_limit') | float)) %}
            0
          {% else %}
            1
          {% endif %}

      water_consumption_monthly_prediction_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if ((states('sensor.water_meter_16452690_consumption_predication') == 'unavailable') or (states('sensor.water_meter_16452690_consumption_predication') == 'unknown') or (states('sensor.water_consumption_monthly_prediction') | float) < (states('input_number.water_consumption_monthly_prediciton_limit') | float)) %}
            0
          {% else %}
            1
          {% endif %}

      water_consumption_monthly_prediction:
        icon_template: mdi:water
        value_template: >
          {{ state_attr('sensor.water_meter_16452690_consumption_predication', 'Predication') | replace(" m³", "") | float }}

utility_meter:
  # water_consumption_daily:
  #   source: sensor.water_meter_16452690_last_reading
  #   cycle: daily

  water_consumption_hourly:
    name: Water Consupmtion Hourly
    source: sensor.water_meter_16452690_last_reading
    cycle: hourly
    

input_number:
  water_consumption_monthly_prediciton_limit:
    name: Water Consumption Monthly Prediction Limit
    min: 0.5
    max: 40
    step: 0.5

  water_consumption_monthly_limit:
    name: Water Consumption Monthly Limit
    min: 0.5
    max: 40
    step: 0.5

  water_consumption_daily_limit:
    name: Water Consumption Daily Limit
    min: 0.1
    max: 3
    step: 0.1

  water_consumption_hourly_limit:
    name: Water Consumption Hourly Limit
    min: 0.1
    max: 3
    step: 0.1


###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  - alias: Water Consumption Daily Limit Exceeded
    description: Water Consumption Daily Limit Exceeded
    trigger:
      platform: template
      value_template: "{{ (states('sensor.water_meter_16452690_today_s_consumption') | float) >= (states('input_number.water_consumption_daily_limit') | float) }}"
    condition: []
    action:
      - service: notify.email
        data_template:
          message: Daily water consumption {{ states('sensor.water_meter_16452690_today_s_consumption') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_daily_limit }}[m^3]

  - alias: Water Consumption Hourly Limit Exceeded
    description: Water Consumption Hourly Limit Exceeded
    trigger:
      platform: template
      value_template: "{{ (states('sensor.water_consumption_hourly') | float) >= (states('input_number.water_consumption_hourly_limit') | float) }}"
    condition: []
    action:
      - service: notify.email
        data_template:
          message: Hourly water consumption {{ states('sensor.water_consumption_hourly') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_hourly_limit }}[m^3]

  - alias: Water Consumption Monthly Limit
    description: Water Consumption Monthly Limit
    trigger:
      platform: template
      value_template: "{{ (states('sensor.water_meter_16452690_monthly_consumption') | float) >= (states('input_number.water_consumption_monthly_limit') | float) }}"
    condition: []
    action:
      - service: notify.email
        data_template:
          message: Monthly Prediciton is {{ states('sensor.water_meter_16452690_monthly_consumption') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_monthly_limit }}[m^3]

  - alias: Water Consumption Monthly Prediction Limit
    description: Water Consumption Monthly Prediction Limit
    trigger:
      platform: template
      value_template: "{{ (states('sensor.water_consumption_monthly_prediction') | float) >= (states('input_number.water_consumption_monthly_prediciton_limit') | float) }}"
    condition: []
    action:
      - service: notify.email
        data_template:
          message: Monthly Prediciton is {{ states('sensor.water_consumption_monthly_prediction') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_monthly_prediciton_limit }}[m^3]

###################################
########## S C R I P T S ##########
###################################

# script:
#   # ---------------------
