#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  irrigation_drips_scheduler_enable2:
    name: Enable
    icon: mdi:power
  irrigation_drips_day_sunday2:
    name: Sunday
    icon: mdi:calendar-today
  irrigation_drips_day_monday2:
    name: Monday
    icon: mdi:calendar-today
  irrigation_drips_day_tuesday2:
    name: Tuesday
    icon: mdi:calendar-today
  irrigation_drips_day_wednesday2:
    name: Wednesday
    icon: mdi:calendar-today
  irrigation_drips_day_thursday2:
    name: Thursday
    icon: mdi:calendar-today
  irrigation_drips_day_friday2:
    name: Friday
    icon: mdi:calendar-today
  irrigation_drips_day_saturday2:
    name: Saturday
    icon: mdi:calendar-today


input_datetime:
  irrigation_drips_start_time2:
    name: Start Time
    has_date: false
    has_time: true


input_number:
  irrigation_drips_timer_duration2:
    name: Duration
    unit_of_measurement: "min"
    min: 0
    max: 60
    step: 5


###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:

  # Trigger    - Start Time 2
  # Conditions - Enable on and day-of-week true
  # Actions    - turn on drips, delay timer duration 2, turn of water boiler
  - alias: irrigation_drips_timer2
    description: Water Boiler Timer
    trigger: 
      platform: time
      at: input_datetime.irrigation_drips_start_time2
    condition:
      - condition: state
        entity_id: input_boolean.irrigation_drips_scheduler_enable2
        state: 'on'
      - condition: template
        value_template: >
          {% set sensor_names = [ 'monday', 'tuesday', 'wednesday','thursday','friday','saturday','sunday'] %}
          {% set today_name = sensor_names[now().weekday()] %}
          {% set entity_id = 'input_boolean.irrigation_drips_day_'+today_name+'2' %}
          {{ is_state(entity_id, 'on') }}
    action:
      - service: switch.turn_on
        entity_id: switch.irrigation_drips
      # - delay:
      #     minutes: "{{ states('input_number.irrigation_drips_timer_duration2') | int }}"
      - service: timer.start
        target:
          entity_id: timer.irrigation_drips
        data:
          duration: "{{ ((states('input_number.irrigation_drips_timer_duration2') | int) * 60) | timestamp_custom('%H:%M:%S',False) }}"
      - wait_template: "{{ is_state('timer.irrigation_drips', 'idle' ) }}"
      - service: switch.turn_off
        entity_id: switch.irrigation_drips
