#####################################
########## E N T I T I E S ##########
#####################################

camera:
  - platform: xiaomi_cloud_map_extractor
    name: "Vacuum Bottom"
    host: !secret vacuum_bottom_host
    token: !secret vacuum_bottom_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: !secret xiaomi_country
    draw: ['all']
    attributes:
      - calibration_points
    scan_interval:
      seconds: 60

  - platform: xiaomi_cloud_map_extractor
    name: "Vacuum Top"
    host: !secret vacuum_top_host
    token: !secret vacuum_top_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: !secret xiaomi_country
    draw: ['all']
    attributes:
      - calibration_points
    scan_interval:
      seconds: 60

sensor:
  - platform: template
    sensors:
      vacuum_bottom_problem:
        icon_template: mdi:robot-vacuum
        value_template: >
          {% if has_value('vacuum.vacuum_bottom') %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}
      vacuum_top_problem:
        icon_template: mdi:robot-vacuum
        value_template: >
          {% if has_value('vacuum.vacuum_top') %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}

###########################################
########## A U T O M A T I O N S ##########
###########################################

###################################
########## S C R I P T S ##########
###################################
