#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  irrigation_sprinkler_west_scheduler_enable2:
    name: Enable
    icon: mdi:power
  irrigation_sprinkler_west_day_sunday2:
    name: Sunday
    icon: mdi:calendar-today
  irrigation_sprinkler_west_day_monday2:
    name: Monday
    icon: mdi:calendar-today
  irrigation_sprinkler_west_day_tuesday2:
    name: Tuesday
    icon: mdi:calendar-today
  irrigation_sprinkler_west_day_wednesday2:
    name: Wednesday
    icon: mdi:calendar-today
  irrigation_sprinkler_west_day_thursday2:
    name: Thursday
    icon: mdi:calendar-today
  irrigation_sprinkler_west_day_friday2:
    name: Friday
    icon: mdi:calendar-today
  irrigation_sprinkler_west_day_saturday2:
    name: Saturday
    icon: mdi:calendar-today

input_datetime:
  irrigation_sprinkler_west_start_time2:
    name: Start Time
    has_date: false
    has_time: true

input_number:
  irrigation_sprinkler_west_timer_duration2:
    name: Duration
    unit_of_measurement: "min"
    min: 0
    max: 30
    step: 5

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  description: "Irrigation Sprinkler West Scheduler 2"
  alias: irrigation_sprinkler_west_scheduler2
  use_blueprint:
    path: blueprint_irrigation_scheduler.yaml
    input:
      start_time: input_datetime.irrigation_sprinkler_west_start_time2
      scheduler_enable: input_boolean.irrigation_sprinkler_west_scheduler_enable2
      switch: switch.irrigation_sprinkler_west
      timer: timer.irrigation_sprinkler_west
      duration: input_number.irrigation_sprinkler_west_timer_duration2
      scheduler_number: 2

###################################
########## S C R I P T S ##########
###################################

# script:
# # ---------------------
