#####################################
########## E N T I T I E S ##########
#####################################

sensor:
  - platform: template
    sensors:
      boiler_switch_problem:
        icon_template: mdi:water-boiler-off
        value_template: >
          {% if (has_value('switch.boiler_switch')) %}
            {{ 0 }}
          {% else %}
            {{ 1 }}
          {% endif %}

input_number:
  boiler_switch_duration:
    name: Duration
    unit_of_measurement: "min"
    #    initial: 30
    min: 0
    max: 240
    step: 5
  boiler_disable_schedulers_temperature:
    name: Water Boiler Disable Schedulers Temperature
    unit_of_measurement: "ºC"
    #    initial: 25
    min: 40
    max: 70
    step: 1

input_boolean:
  boiler_switch_immediate:
    name: Water Boiler Immediate
    icon: mdi:power
  boiler_switch_future:
    name: Water Boiler Future
    icon: mdi:timer-outline

timer:
  boiler_switch:
    name: Time Left
    icon: mdi:timer-outline

input_datetime:
  boiler_switch_start_time:
    name: Start Time
    has_time: true
    has_date: false

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  # Trigger    - HA initializing
  # Conditions - NONE
  # Actions    - Turn off water boiler (in case HA restarts during a heating cycle)
  - alias: Irrigataion Initialization
    description: Update enitity values upon HA start
    trigger:
      event: start
      platform: homeassistant
    condition: []
    action:
      - entity_id: switch.boiler_switch
        service: switch.turn_off

  # Trigger    - Manual turn ON Water Boiler Button
  # Conditions - NONE
  # Actions    - Start Boiler Manual Timer
  #            - Turn ON Boiler Switch
  - alias: Boiler Start Manual Immediate Cycle
    description: BLA BLA BLA
    trigger:
      platform: state
      entity_id: input_boolean.boiler_switch_immediate
      to: "on"
    condition: []
    action:
      - service: timer.start
        data:
          entity_id: timer.boiler_switch
          duration:
            minutes: "{{ states('input_number.boiler_switch_duration') | int }}"
      - service: switch.turn_on
        entity_id: switch.boiler_switch

  # Trigger    - Future start time
  # Conditions - Future enabled
  # Actions    - Start Boiler Timer
  #            - Turn ON Boiler Switch
  - alias: Boiler Start Manual Future Cycle
    description: BLA BLA BLA
    trigger:
      platform: time
      at: input_datetime.boiler_switch_start_time
    condition:
      condition: state
      entity_id: input_boolean.boiler_switch_future
      state: "on"
    action:
      - service: timer.start
        data:
          entity_id: timer.boiler_switch
          duration:
            minutes: "{{ states('input_number.boiler_switch_duration') | int }}"
      - service: switch.turn_on
        entity_id: switch.boiler_switch

  # Trigger    - Manual turn OFF Water Boiler Button
  #            - Water Boiler Timer Expired
  #            - Turn OFF Boiler Switch
  # Conditions - NONE
  # Actions    - Cancel/Stop Boiler Timer
  #            - Turn OFF Boiler Switch
  #            - Turn OFF Water Boiler Button
  - alias: Boiler Stop Manual Cycle
    description: BLA BLA BLA
    trigger:
      - platform: state
        entity_id: timer.boiler_switch
        to: "idle"
      - platform: state
        entity_id: switch.boiler_switch
        to: "off"
      - platform: state
        entity_id: input_boolean.boiler_switch_immediate
        to: "off"
      - platform: state
        entity_id: input_boolean.boiler_switch_future
        to: "off"
    condition: []
    action:
      - service: timer.cancel
        data:
          entity_id: timer.boiler_switch
      - service: switch.turn_off
        entity_id: switch.boiler_switch
      - service: input_boolean.turn_off
        entity_id: input_boolean.boiler_switch_immediate
      - service: input_boolean.turn_off
        entity_id: input_boolean.boiler_switch_future
###################################
########## S C R I P T S ##########
###################################

# script:
#   # ---------------------
