#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  hvac_livingroom_scheduler_enable1:
    name: Enable
    icon: mdi:power

input_datetime:
  hvac_livingroom_start_time1:
    name: Start Time
    has_date: false
    has_time: true

climate:
  - platform: smartir
    name: HVAC Livingroom Virtual 1
    unique_id: hvac_livingroom_virtual1
    device_code: 1621
    controller_data: remote.livingroom_remote
    # temperature_sensor:
    delay: 10

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:

  # Trigger    - Start Time 1
  # Conditions - 
  # Actions    - turn on HVAC
  - alias: hvac_livingroom_start1
    #description: HVAC livingroom Start 1
    trigger: 
      platform: time
      at: input_datetime.hvac_livingroom_start_time1
    condition:
      - condition: state
        entity_id: input_boolean.hvac_livingroom_scheduler_enable1
        state: 'on'
    action:
      - service: notify.file_debug
        data:
          message: "HVAC Livingroom 1 - {{ states('input_boolean.hvac_livingroom_scheduler_enable1') }} - {{ state_attr('climate.hvac_livingroom_virtual_1', 'temperature') }}/{{ state_attr('climate.hvac_livingroom_virtual_1', 'fan_mode') }}/{{ states('climate.hvac_livingroom_virtual_1') }}"
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hvac_livingroom
          fan_mode: "{{ state_attr('climate.hvac_livingroom_virtual_1', 'fan_mode') }}"
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hvac_livingroom
          temperature: "{{ state_attr('climate.hvac_livingroom_virtual_1', 'temperature') | float }}"
          hvac_mode: "{{ states('climate.hvac_livingroom_virtual_1') }}"
      - service: input_boolean.turn_off
        entity_id: input_boolean.hvac_livingroom_scheduler_enable1