#####################################
########## E N T I T I E S ##########
#####################################

input_boolean:
  boiler_switch_scheduler_enable1:
    name: Enable
    icon: mdi:power
  boiler_switch_day_sunday1:
    name: Sunday
    icon: mdi:calendar-today
  boiler_switch_day_monday1:
    name: Monday
    icon: mdi:calendar-today
  boiler_switch_day_tuesday1:
    name: Tuesday
    icon: mdi:calendar-today
  boiler_switch_day_wednesday1:
    name: Wednesday
    icon: mdi:calendar-today
  boiler_switch_day_thursday1:
    name: Thursday
    icon: mdi:calendar-today
  boiler_switch_day_friday1:
    name: Friday
    icon: mdi:calendar-today
  boiler_switch_day_saturday1:
    name: Saturday
    icon: mdi:calendar-today


input_datetime:
  boiler_switch_start_time1:
    name: Start Time
    has_date: false
    has_time: true


input_number:
  boiler_switch_timer_duration1:
    name: Duration
    unit_of_measurement: "min"
    min: 0
    max: 180
    step: 5


###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:

  # Trigger    - Start Time 1
  # Conditions - Enable on and day-of-week true
  # Actions    - turn on water boiler, delay timer duration 1, turn of water boiler
  - alias: boiler_switch_timer1
    description: Water Boiler Timer
    trigger: 
      platform: time
      at: input_datetime.boiler_switch_start_time1
    condition:
      - condition: state
        entity_id: input_boolean.boiler_switch_scheduler_enable1
        state: 'on'
      - condition: template
        value_template: >
          {% set sensor_names = [ 'monday', 'tuesday', 'wednesday','thursday','friday','saturday','sunday'] %}
          {% set today_name = sensor_names[now().weekday()] %}
          {% set entity_id = 'input_boolean.boiler_switch_day_'+today_name+'1' %}
          {{ is_state(entity_id, 'on') }}
      - condition: numeric_state
        #entity_id: sensor.accuweather_realfeel_temperature_max_0d
        entity_id: sensor.water_boiler_temperature_in_from_panel
        below: input_number.boiler_disable_schedulers_temperature
    action:
      - service: switch.turn_on
        entity_id: switch.boiler_switch
      - delay:
          minutes: "{{ states('input_number.boiler_switch_timer_duration1') | int }}"
      - service: switch.turn_off
        entity_id: switch.boiler_switch


###################################
########## S C R I P T S ##########
###################################

# script:
#   # ---------------------
