#####################################
########## E N T I T I E S ##########
#####################################

sensor:
  - platform: template
    sensors:
      water_consumption_daily_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if has_value('sensor.citymind_16452690_meter_today_s_consumption') and ((states('sensor.citymind_16452690_meter_today_s_consumption') | float(default=0)) > (states('input_number.water_consumption_daily_limit') | float(default=0))) %}
            'on'
          {% else %}
            'off'
          {% endif %}

      water_consumption_hourly_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if has_value('sensor.water_consumption_hourly') and ((states('sensor.water_consumption_hourly') | float(default=0)) > (states('input_number.water_consumption_hourly_limit') | float(default=0))) %}
            'on'
          {% else %}
            'off'
          {% endif %}

      water_consumption_monthly_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if has_value('sensor.citymind_16452690_meter_monthly_consumption') and ((states('sensor.citymind_16452690_meter_monthly_consumption') | float(default=0)) > (states('input_number.water_consumption_monthly_limit') | float(default=0))) %}
            'on'
          {% else %}
            'off'
          {% endif %}

      water_consumption_monthly_forecast_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if has_value('sensor.citymind_16452690_meter_consumption_forecast') and ((states('sensor.water_consumption_monthly_forecast') | float(default=0)) > (states('input_number.water_consumption_monthly_forecast_limit') | float(default=0))) %}
            'on'
          {% else %}
            'off'
          {% endif %}

      water_consumption_limit_exceeded:
        icon_template: mdi:water-alert
        value_template: >
          {% if ( (states('sensor.water_consumption_daily_limit_exceeded') == 'on') or (states('sensor.water_consumption_hourly_limit_exceeded') == 'on') or (states('sensor.water_consumption_monthly_limit_exceeded') == 'on') or (states('sensor.water_consumption_monthly_forecast_limit_exceeded') == 'on') ) %}
            1
          {% else %}
            0
          {% endif %}

utility_meter:
  water_consumption_hourly:
    name: Water Consumption Hourly
    source: sensor.citymind_16452690_meter_last_read
    cycle: hourly

input_number:
  water_consumption_monthly_forecast_limit:
    name: Water Consumption Monthly Forecast Limit
    min: 0.5
    max: 40
    step: 0.5

  water_consumption_monthly_limit:
    name: Water Consumption Monthly Limit
    min: 0.5
    max: 40
    step: 0.5

  water_consumption_daily_limit:
    name: Water Consumption Daily Limit
    min: 0.1
    max: 3
    step: 0.1

  water_consumption_hourly_limit:
    name: Water Consumption Hourly Limit
    min: 0.1
    max: 3
    step: 0.1

###########################################
########## A U T O M A T I O N S ##########
###########################################

automation:
  - alias: Water Consumption Daily Limit Exceeded
    description: Water Consumption Daily Limit Exceeded
    trigger:
      platform: state
      entity_id: sensor.water_consumption_daily_limit_exceeded
      to: 'on'
    condition: []
    action:
      - service: notify.email
        data:
          message: Daily water consumption {{ states('sensor.sensor.citymind_16452690_meter_today_s_consumption') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_daily_limit }}[m^3]

  - alias: Water Consumption Hourly Limit Exceeded
    description: Water Consumption Hourly Limit Exceeded
    trigger:
      platform: state
      entity_id: sensor.water_consumption_hourly_limit_exceeded
      to: 'on'
    condition: []
    action:
      - service: notify.email
        data:
          message: Hourly water consumption {{ states('sensor.water_consumption_hourly') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_hourly_limit }}[m^3]

  - alias: Water Consumption Monthly Limit
    description: Water Consumption Monthly Limit
    trigger:
      platform: state
      entity_id: sensor.water_consumption_monthly_limit_exceeded
      to: 'on'
    condition: []
    action:
      - service: notify.email
        data:
          message: Monthly forecast is {{ states('sensor.citymind_16452690_meter_monthly_consumption') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_monthly_limit }}[m^3]

  - alias: Water Consumption Monthly Forecast Limit
    description: Water Consumption Monthly Forecast Limit
    trigger:
      platform: state
      entity_id: sensor.water_consumption_monthly_forecast_limit_exceeded
      to: 'on'
    condition: []
    action:
      - service: notify.email
        data:
          message: Monthly forecast is {{ states('sensor.water_consumption_monthly_forecast') }}[m^3] reached/exceeded limit {{ input_number.water_consumption_monthly_forecast_limit }}[m^3]

###################################
########## S C R I P T S ##########
###################################

# script:
#   # ---------------------
